-- =====================================================================
-- Hotel ERP — initial schema
-- Snake_case to match Spring's CamelCaseToUnderscoresNamingStrategy.
-- Money is numeric(10,2). Enums are stored as varchar (EnumType.STRING).
-- =====================================================================

-- Needed for the daterange overlap exclusion constraint on bookings.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------
-- Reference / identity
-- ---------------------------------------------------------------------
CREATE TABLE category (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80)  NOT NULL UNIQUE,
    star_rating  SMALLINT     NOT NULL CHECK (star_rating BETWEEN 1 AND 5),
    description  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE hotel (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    address      VARCHAR(200) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    country      VARCHAR(100) NOT NULL,
    phone        VARCHAR(40),
    email        VARCHAR(160),
    description  VARCHAR(1000),
    image_url    VARCHAR(500),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    category_id  BIGINT       NOT NULL REFERENCES category(id),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_hotel_city ON hotel(city);
CREATE INDEX idx_hotel_category ON hotel(category_id);

CREATE TABLE room (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number                 VARCHAR(20)   NOT NULL,
    floor                  SMALLINT,
    type                   VARCHAR(20)   NOT NULL,   -- RoomType
    status                 VARCHAR(20)   NOT NULL,   -- RoomStatus
    capacity               SMALLINT      NOT NULL CHECK (capacity BETWEEN 1 AND 10),
    description            VARCHAR(500),
    image_url              VARCHAR(500),
    price_per_night        NUMERIC(10,2) NOT NULL CHECK (price_per_night >= 0),
    half_board_supplement  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (half_board_supplement >= 0),
    full_board_supplement  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (full_board_supplement >= 0),
    hotel_id               BIGINT        NOT NULL REFERENCES hotel(id),
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_room_number_per_hotel UNIQUE (hotel_id, number)
);
CREATE INDEX idx_room_hotel ON room(hotel_id);
CREATE INDEX idx_room_status ON room(status);

-- ---------------------------------------------------------------------
-- Users & auth
-- ---------------------------------------------------------------------
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,   -- Role
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(100) NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_refresh_token_user ON refresh_token(user_id);

-- ---------------------------------------------------------------------
-- People (Person is a @MappedSuperclass — separate tables, no shared id)
-- ---------------------------------------------------------------------
CREATE TABLE client (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(80)  NOT NULL,
    last_name     VARCHAR(80)  NOT NULL,
    document_id   VARCHAR(40)  NOT NULL UNIQUE,
    birth_date    DATE,
    phone         VARCHAR(40),
    address       VARCHAR(200),
    client_type   VARCHAR(20)  NOT NULL,   -- ClientType
    registered_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    user_id       BIGINT       UNIQUE REFERENCES app_user(id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE employee (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(80)  NOT NULL,
    last_name    VARCHAR(80)  NOT NULL,
    document_id  VARCHAR(40)  NOT NULL UNIQUE,
    birth_date   DATE,
    phone        VARCHAR(40),
    address      VARCHAR(200),
    position     VARCHAR(20)   NOT NULL,   -- EmployeePosition
    status       VARCHAR(20)   NOT NULL,   -- EmployeeStatus
    hired_at     DATE          NOT NULL,
    gross_salary NUMERIC(10,2) CHECK (gross_salary >= 0),
    hotel_id     BIGINT        REFERENCES hotel(id),
    user_id      BIGINT        UNIQUE REFERENCES app_user(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_employee_hotel ON employee(hotel_id);

-- ---------------------------------------------------------------------
-- Bookings & invoices
-- ---------------------------------------------------------------------
CREATE TABLE booking (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(30)   NOT NULL UNIQUE,
    check_in_date  DATE          NOT NULL,
    check_out_date DATE          NOT NULL,
    guests         SMALLINT      NOT NULL CHECK (guests >= 1),
    board_type     VARCHAR(20)   NOT NULL,   -- BoardType
    status         VARCHAR(20)   NOT NULL,   -- BookingStatus
    total_price    NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
    notes          VARCHAR(1000),
    room_id        BIGINT        NOT NULL REFERENCES room(id),
    client_id      BIGINT        NOT NULL REFERENCES client(id),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_booking_dates CHECK (check_out_date > check_in_date)
);
CREATE INDEX idx_booking_room ON booking(room_id);
CREATE INDEX idx_booking_client ON booking(client_id);
CREATE INDEX idx_booking_status ON booking(status);

-- DB-level double-booking safety net: no two active bookings for the same
-- room can have overlapping [check_in, check_out) ranges.
ALTER TABLE booking ADD CONSTRAINT excl_booking_no_overlap
    EXCLUDE USING gist (
        room_id WITH =,
        daterange(check_in_date, check_out_date, '[)') WITH &&
    ) WHERE (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN'));

CREATE TABLE invoice (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(30)   NOT NULL UNIQUE,
    issued_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    subtotal       NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    vat_rate       NUMERIC(5,4)  NOT NULL CHECK (vat_rate >= 0),
    vat_amount     NUMERIC(10,2) NOT NULL CHECK (vat_amount >= 0),
    total          NUMERIC(10,2) NOT NULL CHECK (total >= 0),
    payment_method VARCHAR(20)   NOT NULL,   -- PaymentMethod
    status         VARCHAR(20)   NOT NULL,   -- InvoiceStatus
    booking_id     BIGINT        NOT NULL UNIQUE REFERENCES booking(id),
    client_id      BIGINT        NOT NULL REFERENCES client(id),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_invoice_client ON invoice(client_id);

-- ---------------------------------------------------------------------
-- Housekeeping / maintenance tasks
-- ---------------------------------------------------------------------
CREATE TABLE task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150) NOT NULL,
    description  VARCHAR(1000),
    type         VARCHAR(20)  NOT NULL,   -- TaskType
    status       VARCHAR(20)  NOT NULL,   -- TaskStatus
    priority     VARCHAR(20)  NOT NULL,   -- TaskPriority
    due_date     DATE,
    completed_at TIMESTAMPTZ,
    room_id      BIGINT       REFERENCES room(id),
    hotel_id     BIGINT       NOT NULL REFERENCES hotel(id),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_task_hotel ON task(hotel_id);
CREATE INDEX idx_task_status ON task(status);

-- Task <-> Employee assignment (N:M)
CREATE TABLE task_assignee (
    task_id     BIGINT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, employee_id)
);
